const cardsHome = [
  {name:"Otto von Bismarck", cp:"3", number:1, image:"Home Card 1 GE.png", type:"Home", spec:`Otto von Bismarck. Gain 1 stability. Declare a war of unification using this card’s CP value. You may target two different powers with this declaration of war. After declaring war you may choose to forbid other players from joining the war. Minor power allies may join the war as normal. Clarification: Remember that declaring war on a minor power with a player ally still counts as declaring war on that player [13.4]. This event can prevent that player from calling their player allies, but the defending player will still have the option to aid their minor power ally.`},
  {name:"German General Staff", cp:"3", number:2, image:"Home Card 2 GE.png", type:"Home", spec:`German General Staff. Gain 1 stability. Take any response or combat card from the discard pile. It cannot be played this impulse. Gain 1 stability and two elite corps.`},
  {name:"Sun Never Sets", cp:"3", number:3, image:"Home Card 3 UK.png", type:"Home", spec:`Sun Never Sets. Gain 1 stability. Build 1 naval squadron or Dreadnought and then spend 2 CP on expeditionary force, pacification, and/or naval movement actions. Flip the Indian Stability marker to its “Stable” side. Spend up to 2 CP to build Indian army steps or an EF in India or Bengal. Place the Indian Fort in India or upgrade it to level 2. This is a special fort that does not degrade during the end phase but can only be built or upgraded using this card.`},
  {name:"Balance of Power", cp:"3", number:4, image:"Home Card 4 UK.png", type:"Home", spec:`Balance of Power. Gain 1 stability. If the defender agrees, you become the primary belligerent and you enter the war on the defending side. Use this card’s CP value for your CP war budget. If you enter the war, draw a card at the end of the war. One player (your choice) that you invited (and that joined) also draws a card at the end of the war. Additionally, if intervening to help the Ottomans, take control of an Ottoman naval base in the Eastern Mediterranean as soon as you enter the war. If the defender does not agree draw a card. Playable as an event to gain 1 stability. Draw a card. Play when another player declares war. Cannot be played in response to Otto von Bismarck.`},
  {name:"The City of Light", cp:"3", number:5, image:"Home Card 5 FR.png", type:"Home", spec:`The City of Light. Gain 1 stability and 3 CP to spend. Roll a die. If the result is less than or equal to the current turn gain 1 City of Light point. Before rolling, you may forgo X CP to apply a -X DRM to the die roll.`},
  {name:"Aux Armes, Citoyens!", cp:"3", number:6, image:"Home Card 6 FR.png", type:"Home", spec:`Aux Armes, Citoyens!. Gain 2 reserve army steps, then declare war using this card’s CP value. If you choose a conquest war aim you may target up to two keys and you may also target two different powers. However, if you do either, neutral powers can join the war against you. If France wins the war gain 1 stability. Take either the French Intervention or Papal Influence card from the discard pile. You may play it immediately.`},
  {name:"Habsburg Dynasty", cp:"3", number:7, image:"Home Card 7 AU.png", type:"Home", spec:`Habsburg Dynasty. Choose an independent minor power in Europe. Remove an opposing player’s diplomacy marker, if present and gain an alliance with that minor power. Special: If you choose a German minor power (Bavaria, Saxony or Hanover) you may remove an opposing player’s alliance marker from the chosen space. After playing this card, if you’re allied with at least two German minor powers gain a + 1 card marker.`},
  {name:"Kaiserreich", cp:"3", number:8, image:"Home Card 8 AU.png", type:"Home", spec:`Kaiserreich. Gain 1 stability. Grant rights to a nationality. Gain 1 stability. Attempt to grant citizenship to a nationality that already has rights. Roll one die. A roll ≥ 3 succeeds. Increase the difficulty of the roll by one for each nationality that already has citizenship. Before rolling, you may forgo the stability increase to apply a +2 DRM to the citizenship roll. Playable after Dual Monarchy has been played`},
  {name:"Russo-Turkish Wars", cp:"3", number:9, image:"Home Card 9 RU.png", type:"Home", spec:`Russo-Turkish Wars. If possible, gain an alliance with a minor power in the Balkans with which you have a diplomacy marker. Then declare war against the Ottomans using this card’s CP value. If a liberation war aim is chosen, this card can liberate Balkan nationalities that are not currently in rebellion. If a conquest war aim is chosen, do not increase the WTT or decrease your stability. If Russia wins the war gain 1 stability.`},
  {name:"God Save the Tsar", cp:"3", number:10, image:"Home Card 10 RU.png", type:"Home", spec:`God Save the Tsar. Gain 1 stability. Spend 4 CP on recruitment and construct fort actions (you can only gain 1 elite corps through this event). Gain 1 stability. Attempt to build the Trans-Siberian Railroad. Roll a die, if your roll is less than or equal to the current turn the RR is complete.`},
  {name:"Modernization", cp:"3", number:11, image:"Home Card 11 OT.png", type:"Home", spec:`Modernization. Gain 1 stability. Another player can give you a card to put into industrialization, that power draws a card. They must tell you the true CP value of the card they are giving you. If no player gives you a card you may use this card for 3 CP.`},
  {name:"Jihad", cp:"3", number:12, image:"Home Card 12 OT.png", type:"Home", spec:`Jihad. Declare war against a power that controls an OT home space or RU using this card’s CP value (declaring war on a RU Minor power ally counts as declaring war on RU). Do not increase the WTT or decrease your stability. Gain 2 Jihad markers (your player display explains how Jihad markers function). Gain 1 stability if you win the war.`},
];
