const cardsGW = [
  {name:"Minor Power Entry", cp:1, number:1, image:"GW Event/1.jpg", type:"GW Event", spec:`Minor Power Entry. Choose an independent minor power and roll a die. On a roll ≥3 that power joins the GW on a side of your choice. This event cannot cause a minor power to join the war against its pre-GW player ally (Exception: Balkan powers do not follow this rule). The minor power gains one army (if able). Choose a member of their alliance to control the minor power, place that player’s alliance marker in the minor power’s space. When a power enters the GW their units cannot move or attack until after the active player’s next impulse; place this card in front of the active player as a reminder and discard it at the end of the active players next turn. Place a strict neutrality marker on a minor power. Powers with a strict neutrality marker cannot join the GW.`},
  {name:"Major Power Entry", cp:1, number:2, image:"GW Event/2.jpg", type:"GW Event", spec:`Major Power Entry. Choose to shift either Italy or the US on the Alliance Track. If Italy is chosen roll a die, on a 4-6 Italy shifts into the chosen alliance and joins the GW, otherwise this event has no effect. If the US is chosen it automatically shifts into the chosen alliance. However, the US will only join the GW once it reaches the committed box. See 32.1 for the US setup. When a power enters the GW their units cannot move or attack until after the active player’s next impulse; place this card in front of the active player as a reminder and discard it at the end of the active players next turn. Remove from the game and draw another card if neither Italy nor the US can join the GW. Cannot be played on GW turn 0`},
  {name:"Technological Terror", cp:1, number:3, image:"GW Event/3.jpg", type:"GW Event", spec:`Technological Terror. Gain a +2 land battle modifier during this battle, after the battle place this card face down in front of your opponent. If attacking during or after GW turn 3: gain a +2 land battle modifier and cancel all the effects of trenches in this battle. After the battle place this card face down in front of your opponent. Play at the start of a land battle in which you are the attacker`},
  {name:"Dawn of Modern Warfare", cp:1, number:4, image:"GW Event/4.jpg", type:"GW Event", spec:`Dawn of Modern Warfare. Gain a +2 land battle modifier during this battle, after the battle place this card face down in front of your opponent. If attacking during or after GW turn 3: gain a +2 land battle modifier and cancel all the effects of trenches in this battle. After the battle place this card face down in front of your opponent. Play at the start of a land battle in which you are the attacker`},
  {name:"Capable Commander", cp:1, number:5, image:"GW Event/5.jpg", type:"GW Event", spec:`Capable Commander. Force a player to reroll their battle die. Playable as a normal event or a response card (at the start of a player’s impulse) to flip a facedown GW combat card faceup. Play during a battle after dice have been rolled`},
  {name:"They Shall Not Pass", cp:1, number:6, image:"GW Event/6.jpg", type:"GW Event", spec:`They Shall Not Pass. The losing units do not retreat and remain in the space. Play when a player is forced to retreat out of a space`},
  {name:"Submarines", cp:1, number:7, image:"GW Event/7.jpg", type:"GW Event", spec:`Submarines. Choose a player that is not currently blockaded and was not blockaded last turn, then roll a die. Prior to rolling, you may to add a +2 or -2 DRM to your roll. Apply the following results: 1-3 lower the chosen player’s war budget by 1 4-5 lower the chosen player’s war budget by 2 6 lower the chosen player’s war budget by 2, and shift the US alliance chit towards the chosen player’s alliance. Remember, the US must shift into a committed box in order to enter the GW. Exception: on results 4-6 the second war budget loss cannot reduce a player’s war budget below 1.`},
  {name:"Political Pressure", cp:1, number:8, image:"GW Event/8.jpg", type:"GW Event", spec:`Political Pressure. Choose a player with a war budget of at least 2 CP. That player must make an attack later this turn. If they do not make an attack they lose one stability at the end of this GW turn. This card can only mandate that a land battle takes place and a player that is not adjacent to any enemy armies can neither be targeted nor affected by this event. Occupying an empty key that was controlled (or occupied) by an enemy power also counts as satisfying the attack condition for this event.`},
  {name:"Political Pressure", cp:1, number:9, image:"GW Event/9.jpg", type:"GW Event", spec:`Political Pressure. Choose a player with a war budget of at least 2 CP. That player must make an attack later this turn. If they do not make an attack they lose one stability at the end of this GW turn. This card can only mandate that a land battle takes place and a player that is not adjacent to any enemy armies can neither be targeted nor affected by this event. Occupying an empty key that was controlled (or occupied) by an enemy power also counts as satisfying the attack condition for this event.`},
];
